/**
 * generated by Xtext 2.13.0
 */
package esir.compilation.whdsl.impl;

import esir.compilation.whdsl.Definition;
import esir.compilation.whdsl.InOutput;
import esir.compilation.whdsl.WhdslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link esir.compilation.whdsl.impl.DefinitionImpl#getInoutput <em>Inoutput</em>}</li>
 *   <li>{@link esir.compilation.whdsl.impl.DefinitionImpl#getInoutput2 <em>Inoutput2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DefinitionImpl extends MinimalEObjectImpl.Container implements Definition
{
  /**
   * The cached value of the '{@link #getInoutput() <em>Inoutput</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInoutput()
   * @generated
   * @ordered
   */
  protected InOutput inoutput;

  /**
   * The cached value of the '{@link #getInoutput2() <em>Inoutput2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInoutput2()
   * @generated
   * @ordered
   */
  protected InOutput inoutput2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WhdslPackage.Literals.DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InOutput getInoutput()
  {
    return inoutput;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInoutput(InOutput newInoutput, NotificationChain msgs)
  {
    InOutput oldInoutput = inoutput;
    inoutput = newInoutput;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhdslPackage.DEFINITION__INOUTPUT, oldInoutput, newInoutput);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInoutput(InOutput newInoutput)
  {
    if (newInoutput != inoutput)
    {
      NotificationChain msgs = null;
      if (inoutput != null)
        msgs = ((InternalEObject)inoutput).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhdslPackage.DEFINITION__INOUTPUT, null, msgs);
      if (newInoutput != null)
        msgs = ((InternalEObject)newInoutput).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhdslPackage.DEFINITION__INOUTPUT, null, msgs);
      msgs = basicSetInoutput(newInoutput, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhdslPackage.DEFINITION__INOUTPUT, newInoutput, newInoutput));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InOutput getInoutput2()
  {
    return inoutput2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInoutput2(InOutput newInoutput2, NotificationChain msgs)
  {
    InOutput oldInoutput2 = inoutput2;
    inoutput2 = newInoutput2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhdslPackage.DEFINITION__INOUTPUT2, oldInoutput2, newInoutput2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInoutput2(InOutput newInoutput2)
  {
    if (newInoutput2 != inoutput2)
    {
      NotificationChain msgs = null;
      if (inoutput2 != null)
        msgs = ((InternalEObject)inoutput2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhdslPackage.DEFINITION__INOUTPUT2, null, msgs);
      if (newInoutput2 != null)
        msgs = ((InternalEObject)newInoutput2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhdslPackage.DEFINITION__INOUTPUT2, null, msgs);
      msgs = basicSetInoutput2(newInoutput2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhdslPackage.DEFINITION__INOUTPUT2, newInoutput2, newInoutput2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WhdslPackage.DEFINITION__INOUTPUT:
        return basicSetInoutput(null, msgs);
      case WhdslPackage.DEFINITION__INOUTPUT2:
        return basicSetInoutput2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WhdslPackage.DEFINITION__INOUTPUT:
        return getInoutput();
      case WhdslPackage.DEFINITION__INOUTPUT2:
        return getInoutput2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WhdslPackage.DEFINITION__INOUTPUT:
        setInoutput((InOutput)newValue);
        return;
      case WhdslPackage.DEFINITION__INOUTPUT2:
        setInoutput2((InOutput)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WhdslPackage.DEFINITION__INOUTPUT:
        setInoutput((InOutput)null);
        return;
      case WhdslPackage.DEFINITION__INOUTPUT2:
        setInoutput2((InOutput)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WhdslPackage.DEFINITION__INOUTPUT:
        return inoutput != null;
      case WhdslPackage.DEFINITION__INOUTPUT2:
        return inoutput2 != null;
    }
    return super.eIsSet(featureID);
  }

} //DefinitionImpl
