/*
 * generated by Xtext 2.13.0
 */
package esir.compilation.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class WhdslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "esir.compilation.Whdsl.Program");
		private final Assignment cFunctionAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cFunctionFunctionParserRuleCall_0 = (RuleCall)cFunctionAssignment.eContents().get(0);
		
		//Program:
		//	function+=Function*;
		@Override public ParserRule getRule() { return rule; }
		
		//function+=Function*
		public Assignment getFunctionAssignment() { return cFunctionAssignment; }
		
		//Function
		public RuleCall getFunctionFunctionParserRuleCall_0() { return cFunctionFunctionParserRuleCall_0; }
	}
	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "esir.compilation.Whdsl.Function");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFunctionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSymbolAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSymbolSYMBOLETerminalRuleCall_1_0 = (RuleCall)cSymbolAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDefinitionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDefinitionDefinitionParserRuleCall_3_0 = (RuleCall)cDefinitionAssignment_3.eContents().get(0);
		
		//Function:
		//	'function' symbol=SYMBOLE ':' definition=Definition;
		@Override public ParserRule getRule() { return rule; }
		
		//'function' symbol=SYMBOLE ':' definition=Definition
		public Group getGroup() { return cGroup; }
		
		//'function'
		public Keyword getFunctionKeyword_0() { return cFunctionKeyword_0; }
		
		//symbol=SYMBOLE
		public Assignment getSymbolAssignment_1() { return cSymbolAssignment_1; }
		
		//SYMBOLE
		public RuleCall getSymbolSYMBOLETerminalRuleCall_1_0() { return cSymbolSYMBOLETerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//definition=Definition
		public Assignment getDefinitionAssignment_3() { return cDefinitionAssignment_3; }
		
		//Definition
		public RuleCall getDefinitionDefinitionParserRuleCall_3_0() { return cDefinitionDefinitionParserRuleCall_3_0; }
	}
	public class DefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "esir.compilation.Whdsl.Definition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReadKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cInoutputAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInoutputInOutputParserRuleCall_1_0 = (RuleCall)cInoutputAssignment_1.eContents().get(0);
		private final Keyword cPercentSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPercentSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cWriteKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cInoutput2Assignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cInoutput2InOutputParserRuleCall_5_0 = (RuleCall)cInoutput2Assignment_5.eContents().get(0);
		
		//Definition:
		//	'read' inoutput=InOutput '%'
		//	'%' 'write' inoutput2=InOutput;
		@Override public ParserRule getRule() { return rule; }
		
		//'read' inoutput=InOutput '%' '%' 'write' inoutput2=InOutput
		public Group getGroup() { return cGroup; }
		
		//'read'
		public Keyword getReadKeyword_0() { return cReadKeyword_0; }
		
		//inoutput=InOutput
		public Assignment getInoutputAssignment_1() { return cInoutputAssignment_1; }
		
		//InOutput
		public RuleCall getInoutputInOutputParserRuleCall_1_0() { return cInoutputInOutputParserRuleCall_1_0; }
		
		//'%'
		public Keyword getPercentSignKeyword_2() { return cPercentSignKeyword_2; }
		
		//'%'
		public Keyword getPercentSignKeyword_3() { return cPercentSignKeyword_3; }
		
		//'write'
		public Keyword getWriteKeyword_4() { return cWriteKeyword_4; }
		
		//inoutput2=InOutput
		public Assignment getInoutput2Assignment_5() { return cInoutput2Assignment_5; }
		
		//InOutput
		public RuleCall getInoutput2InOutputParserRuleCall_5_0() { return cInoutput2InOutputParserRuleCall_5_0; }
	}
	public class InOutputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "esir.compilation.Whdsl.InOutput");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cVariableAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cVariableVARIABLETerminalRuleCall_0_0_0 = (RuleCall)cVariableAssignment_0_0.eContents().get(0);
		private final Keyword cCommaKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cInoutputAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cInoutputInOutputParserRuleCall_0_2_0 = (RuleCall)cInoutputAssignment_0_2.eContents().get(0);
		private final Assignment cVariable2Assignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cVariable2VARIABLETerminalRuleCall_1_0 = (RuleCall)cVariable2Assignment_1.eContents().get(0);
		
		//InOutput:
		//	variable=VARIABLE ',' inoutput=InOutput | variable2=VARIABLE;
		@Override public ParserRule getRule() { return rule; }
		
		//variable=VARIABLE ',' inoutput=InOutput | variable2=VARIABLE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//variable=VARIABLE ',' inoutput=InOutput
		public Group getGroup_0() { return cGroup_0; }
		
		//variable=VARIABLE
		public Assignment getVariableAssignment_0_0() { return cVariableAssignment_0_0; }
		
		//VARIABLE
		public RuleCall getVariableVARIABLETerminalRuleCall_0_0_0() { return cVariableVARIABLETerminalRuleCall_0_0_0; }
		
		//','
		public Keyword getCommaKeyword_0_1() { return cCommaKeyword_0_1; }
		
		//inoutput=InOutput
		public Assignment getInoutputAssignment_0_2() { return cInoutputAssignment_0_2; }
		
		//InOutput
		public RuleCall getInoutputInOutputParserRuleCall_0_2_0() { return cInoutputInOutputParserRuleCall_0_2_0; }
		
		//variable2=VARIABLE
		public Assignment getVariable2Assignment_1() { return cVariable2Assignment_1; }
		
		//VARIABLE
		public RuleCall getVariable2VARIABLETerminalRuleCall_1_0() { return cVariable2VARIABLETerminalRuleCall_1_0; }
	}
	
	
	private final ProgramElements pProgram;
	private final FunctionElements pFunction;
	private final DefinitionElements pDefinition;
	private final InOutputElements pInOutput;
	private final TerminalRule tVARIABLE;
	private final TerminalRule tSYMBOLE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public WhdslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pFunction = new FunctionElements();
		this.pDefinition = new DefinitionElements();
		this.pInOutput = new InOutputElements();
		this.tVARIABLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "esir.compilation.Whdsl.VARIABLE");
		this.tSYMBOLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "esir.compilation.Whdsl.SYMBOLE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("esir.compilation.Whdsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//	function+=Function*;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Function:
	//	'function' symbol=SYMBOLE ':' definition=Definition;
	public FunctionElements getFunctionAccess() {
		return pFunction;
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}
	
	//Definition:
	//	'read' inoutput=InOutput '%'
	//	'%' 'write' inoutput2=InOutput;
	public DefinitionElements getDefinitionAccess() {
		return pDefinition;
	}
	
	public ParserRule getDefinitionRule() {
		return getDefinitionAccess().getRule();
	}
	
	//InOutput:
	//	variable=VARIABLE ',' inoutput=InOutput | variable2=VARIABLE;
	public InOutputElements getInOutputAccess() {
		return pInOutput;
	}
	
	public ParserRule getInOutputRule() {
		return getInOutputAccess().getRule();
	}
	
	//terminal VARIABLE:
	//	'A'..'Z'*;
	public TerminalRule getVARIABLERule() {
		return tVARIABLE;
	}
	
	//terminal SYMBOLE:
	//	'a'..'z'*;
	public TerminalRule getSYMBOLERule() {
		return tSYMBOLE;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
