/**
 * generated by Xtext 2.13.0
 */
package esir.compilation.ui.contentassist;

import esir.compilation.ui.contentassist.AbstractWhdslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class WhdslProposalProvider extends AbstractWhdslProposalProvider {
}
