/**
 * generated by Xtext 2.10.0
 */
package esir.compilation.whdsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Commands</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link esir.compilation.whdsl.Commands#getCommande <em>Commande</em>}</li>
 * </ul>
 *
 * @see esir.compilation.whdsl.WhdslPackage#getCommands()
 * @model
 * @generated
 */
public interface Commands extends EObject
{
  /**
   * Returns the value of the '<em><b>Commande</b></em>' containment reference list.
   * The list contents are of type {@link esir.compilation.whdsl.Command}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commande</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commande</em>' containment reference list.
   * @see esir.compilation.whdsl.WhdslPackage#getCommands_Commande()
   * @model containment="true"
   * @generated
   */
  EList<Command> getCommande();

} // Commands
