/**
 * generated by Xtext 2.13.0
 */
package esir.compilation.whdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link esir.compilation.whdsl.Definition#getInoutput <em>Inoutput</em>}</li>
 *   <li>{@link esir.compilation.whdsl.Definition#getInoutput2 <em>Inoutput2</em>}</li>
 * </ul>
 *
 * @see esir.compilation.whdsl.WhdslPackage#getDefinition()
 * @model
 * @generated
 */
public interface Definition extends EObject
{
  /**
   * Returns the value of the '<em><b>Inoutput</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inoutput</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inoutput</em>' containment reference.
   * @see #setInoutput(InOutput)
   * @see esir.compilation.whdsl.WhdslPackage#getDefinition_Inoutput()
   * @model containment="true"
   * @generated
   */
  InOutput getInoutput();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.Definition#getInoutput <em>Inoutput</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inoutput</em>' containment reference.
   * @see #getInoutput()
   * @generated
   */
  void setInoutput(InOutput value);

  /**
   * Returns the value of the '<em><b>Inoutput2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inoutput2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inoutput2</em>' containment reference.
   * @see #setInoutput2(InOutput)
   * @see esir.compilation.whdsl.WhdslPackage#getDefinition_Inoutput2()
   * @model containment="true"
   * @generated
   */
  InOutput getInoutput2();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.Definition#getInoutput2 <em>Inoutput2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inoutput2</em>' containment reference.
   * @see #getInoutput2()
   * @generated
   */
  void setInoutput2(InOutput value);

} // Definition
