/**
 * generated by Xtext 2.13.0
 */
package esir.compilation.whdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see esir.compilation.whdsl.WhdslPackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends EObject
{
} // Expr
