/**
 * generated by Xtext 2.13.0
 */
package esir.compilation.whdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link esir.compilation.whdsl.ExprSimple#getNil <em>Nil</em>}</li>
 *   <li>{@link esir.compilation.whdsl.ExprSimple#getVar <em>Var</em>}</li>
 *   <li>{@link esir.compilation.whdsl.ExprSimple#getSym <em>Sym</em>}</li>
 *   <li>{@link esir.compilation.whdsl.ExprSimple#getCons <em>Cons</em>}</li>
 *   <li>{@link esir.compilation.whdsl.ExprSimple#getList <em>List</em>}</li>
 *   <li>{@link esir.compilation.whdsl.ExprSimple#getHd <em>Hd</em>}</li>
 *   <li>{@link esir.compilation.whdsl.ExprSimple#getTl <em>Tl</em>}</li>
 *   <li>{@link esir.compilation.whdsl.ExprSimple#getFuncName <em>Func Name</em>}</li>
 *   <li>{@link esir.compilation.whdsl.ExprSimple#getFuncParams <em>Func Params</em>}</li>
 * </ul>
 *
 * @see esir.compilation.whdsl.WhdslPackage#getExprSimple()
 * @model
 * @generated
 */
public interface ExprSimple extends EObject
{
  /**
   * Returns the value of the '<em><b>Nil</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nil</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nil</em>' attribute.
   * @see #setNil(String)
   * @see esir.compilation.whdsl.WhdslPackage#getExprSimple_Nil()
   * @model
   * @generated
   */
  String getNil();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ExprSimple#getNil <em>Nil</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nil</em>' attribute.
   * @see #getNil()
   * @generated
   */
  void setNil(String value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see esir.compilation.whdsl.WhdslPackage#getExprSimple_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ExprSimple#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

  /**
   * Returns the value of the '<em><b>Sym</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sym</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sym</em>' attribute.
   * @see #setSym(String)
   * @see esir.compilation.whdsl.WhdslPackage#getExprSimple_Sym()
   * @model
   * @generated
   */
  String getSym();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ExprSimple#getSym <em>Sym</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sym</em>' attribute.
   * @see #getSym()
   * @generated
   */
  void setSym(String value);

  /**
   * Returns the value of the '<em><b>Cons</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cons</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cons</em>' containment reference.
   * @see #setCons(LExpr)
   * @see esir.compilation.whdsl.WhdslPackage#getExprSimple_Cons()
   * @model containment="true"
   * @generated
   */
  LExpr getCons();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ExprSimple#getCons <em>Cons</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cons</em>' containment reference.
   * @see #getCons()
   * @generated
   */
  void setCons(LExpr value);

  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(LExpr)
   * @see esir.compilation.whdsl.WhdslPackage#getExprSimple_List()
   * @model containment="true"
   * @generated
   */
  LExpr getList();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ExprSimple#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(LExpr value);

  /**
   * Returns the value of the '<em><b>Hd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hd</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hd</em>' containment reference.
   * @see #setHd(Expr)
   * @see esir.compilation.whdsl.WhdslPackage#getExprSimple_Hd()
   * @model containment="true"
   * @generated
   */
  Expr getHd();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ExprSimple#getHd <em>Hd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hd</em>' containment reference.
   * @see #getHd()
   * @generated
   */
  void setHd(Expr value);

  /**
   * Returns the value of the '<em><b>Tl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tl</em>' containment reference.
   * @see #setTl(Expr)
   * @see esir.compilation.whdsl.WhdslPackage#getExprSimple_Tl()
   * @model containment="true"
   * @generated
   */
  Expr getTl();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ExprSimple#getTl <em>Tl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tl</em>' containment reference.
   * @see #getTl()
   * @generated
   */
  void setTl(Expr value);

  /**
   * Returns the value of the '<em><b>Func Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Func Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func Name</em>' attribute.
   * @see #setFuncName(String)
   * @see esir.compilation.whdsl.WhdslPackage#getExprSimple_FuncName()
   * @model
   * @generated
   */
  String getFuncName();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ExprSimple#getFuncName <em>Func Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func Name</em>' attribute.
   * @see #getFuncName()
   * @generated
   */
  void setFuncName(String value);

  /**
   * Returns the value of the '<em><b>Func Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Func Params</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func Params</em>' containment reference.
   * @see #setFuncParams(LExpr)
   * @see esir.compilation.whdsl.WhdslPackage#getExprSimple_FuncParams()
   * @model containment="true"
   * @generated
   */
  LExpr getFuncParams();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ExprSimple#getFuncParams <em>Func Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func Params</em>' containment reference.
   * @see #getFuncParams()
   * @generated
   */
  void setFuncParams(LExpr value);

} // ExprSimple
