/**
 * generated by Xtext 2.13.0
 */
package esir.compilation.whdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link esir.compilation.whdsl.For#getExprs <em>Exprs</em>}</li>
 *   <li>{@link esir.compilation.whdsl.For#getCmds <em>Cmds</em>}</li>
 * </ul>
 *
 * @see esir.compilation.whdsl.WhdslPackage#getFor()
 * @model
 * @generated
 */
public interface For extends EObject
{
  /**
   * Returns the value of the '<em><b>Exprs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exprs</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exprs</em>' containment reference.
   * @see #setExprs(Exprs)
   * @see esir.compilation.whdsl.WhdslPackage#getFor_Exprs()
   * @model containment="true"
   * @generated
   */
  Exprs getExprs();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.For#getExprs <em>Exprs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exprs</em>' containment reference.
   * @see #getExprs()
   * @generated
   */
  void setExprs(Exprs value);

  /**
   * Returns the value of the '<em><b>Cmds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cmds</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmds</em>' containment reference.
   * @see #setCmds(Commands)
   * @see esir.compilation.whdsl.WhdslPackage#getFor_Cmds()
   * @model containment="true"
   * @generated
   */
  Commands getCmds();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.For#getCmds <em>Cmds</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cmds</em>' containment reference.
   * @see #getCmds()
   * @generated
   */
  void setCmds(Commands value);

} // For
