/**
 * generated by Xtext 2.13.0
 */
package esir.compilation.whdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Each</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link esir.compilation.whdsl.ForEach#getElem <em>Elem</em>}</li>
 *   <li>{@link esir.compilation.whdsl.ForEach#getEnsemb <em>Ensemb</em>}</li>
 *   <li>{@link esir.compilation.whdsl.ForEach#getCommands <em>Commands</em>}</li>
 * </ul>
 *
 * @see esir.compilation.whdsl.WhdslPackage#getForEach()
 * @model
 * @generated
 */
public interface ForEach extends EObject
{
  /**
   * Returns the value of the '<em><b>Elem</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elem</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elem</em>' containment reference.
   * @see #setElem(Expr)
   * @see esir.compilation.whdsl.WhdslPackage#getForEach_Elem()
   * @model containment="true"
   * @generated
   */
  Expr getElem();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ForEach#getElem <em>Elem</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elem</em>' containment reference.
   * @see #getElem()
   * @generated
   */
  void setElem(Expr value);

  /**
   * Returns the value of the '<em><b>Ensemb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ensemb</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ensemb</em>' containment reference.
   * @see #setEnsemb(Expr)
   * @see esir.compilation.whdsl.WhdslPackage#getForEach_Ensemb()
   * @model containment="true"
   * @generated
   */
  Expr getEnsemb();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ForEach#getEnsemb <em>Ensemb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ensemb</em>' containment reference.
   * @see #getEnsemb()
   * @generated
   */
  void setEnsemb(Expr value);

  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commands</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference.
   * @see #setCommands(Commands)
   * @see esir.compilation.whdsl.WhdslPackage#getForEach_Commands()
   * @model containment="true"
   * @generated
   */
  Commands getCommands();

  /**
   * Sets the value of the '{@link esir.compilation.whdsl.ForEach#getCommands <em>Commands</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Commands</em>' containment reference.
   * @see #getCommands()
   * @generated
   */
  void setCommands(Commands value);

} // ForEach
