/**
 * generated by Xtext 2.13.0
 */
package esir.compilation.ide;

import esir.compilation.ide.AbstractWhdslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class WhdslIdeModule extends AbstractWhdslIdeModule {
}
